shows = {'mode7':'https://www.wrek.org/playlist.php/main/24kbs/current/MODE.m3u',
         'goldsoundz':'https://www.wrek.org/playlist.php/main/24kbs/current/GS.m3u',
         'wrekage' : '',
         'not just jazz' : '',
         'crash' : '',
         'battleground' : '',
         'no!': '',
         'shillelagh law' : '',
         'mobius' : '',
         'slow riot' : '',
         'cut and paste': '',
         'friction': '',
         'stonehenge': '',
         'hour of slack':'',
         'coffee and sushi':'',
         'new forces': '',
         'pop up show': '',
         'psych-out': '',

        }
