# Generated by Django 3.0.7 on 2020-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('week', models.IntegerField(default=0)),
            ],
        ),
    ]
